### ISSUE TITLE
Circular import in `transformers`

### ISSUE THREAD

**Issue by kno10** [mudler/LocalAI#1336]
See https://github.com/mudler/LocalAI/pull/1308#discussion_r1405146942_

The `transformers` backend tries to import `transformers.AutoModel`, but shadows `transformers` with its own name.

**Comment by mudler** [comment]
Correct, this fails locally here:

```
Running transformers...
bash run.sh
Traceback (most recent call last):
  File "/home/mudler/_git/LocalAI/backend/python/transformers/transformers.py", line 18, in <module>
    from transformers import AutoModel
  File "/home/mudler/_git/LocalAI/backend/python/transformers/transformers.py", line 18, in <module>
    from transformers import AutoModel
ImportError: cannot import name 'AutoModel' from partially initialized module 'transformers' (most likely due to a circular import) (/home/mudler/_git/LocalAI/backend/python/transformers/transformers.py)
make: *** [Makefile:10: run] Error 1
```

**Comment by mudler** [comment]
good catch @kno10 , thanks!
