### ISSUE TITLE
Bug: PyTorch error with OneApi 2024.1

### ISSUE THREAD

**Issue by fakezeta** [mudler/LocalAI#2153]
**LocalAI version:**
Latest-gpu-intel-f16

**Describe the bug**
Pytorch version installed it's not build with MKL 2024.1

It's related to issue https://github.com/pytorch/pytorch/issues/123097

**Logs**

3:01PM INF Loading model with backend transformers
3:01PM DBG Stopping all backends except ''
3:01PM DBG Loading model in memory from file: /models
3:01PM DBG Loading Model  with gRPC (file: /models) (backend: transformers): {backendString:transformers model: threads:6 assetDir:/tmp/localai/backend_data context:{emptyCtx:{}} gRPCOptions:0xc0001f7a00 externalBackends:map[autogptq:/build/backend/python/autogptq/run.sh bark:/build/backend/python/bark/run.sh coqui:/build/backend/python/coqui/run.sh diffusers:/build/backend/python/diffusers/run.sh exllama:/build/backend/python/exllama/run.sh exllama2:/build/backend/python/exllama2/run.sh huggingface-embeddings:/build/backend/python/sentencetransformers/run.sh mamba:/build/backend/python/mamba/run.sh parler-tts:/build/backend/python/parler-tts/run.sh petals:/build/backend/python/petals/run.sh rerankers:/build/backend/python/rerankers/run.sh sentencetransformers:/build/backend/python/sentencetransformers/run.sh transformers:/build/backend/python/transformers/run.sh transformers-musicgen:/build/backend/python/transformers-musicgen/run.sh vall-e-x:/build/backend/python/vall-e-x/run.sh vllm:/build/backend/python/vllm/run.sh] grpcAttempts:20 grpcAttemptsDelay:2 singleActiveBackend:true parallelRequests:false}
3:01PM DBG Loading external backend: /build/backend/python/transformers/run.sh
3:01PM DBG Loading GRPC Process: /build/backend/python/transformers/run.sh
3:01PM DBG GRPC Service for  will be running at: '127.0.0.1:39389'
3:01PM DBG GRPC Service state dir: /tmp/go-processmanager2019612079
3:01PM DBG GRPC Service Started
3:01PM DBG GRPC(-127.0.0.1:39389): stderr Traceback (most recent call last):
3:01PM DBG GRPC(-127.0.0.1:39389): stderr   File "/build/backend/python/transformers/transformers_server.py", line 19, in <module>
3:01PM DBG GRPC(-127.0.0.1:39389): stderr     import torch
3:01PM DBG GRPC(-127.0.0.1:39389): stderr   File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 235, in <module>
3:01PM DBG GRPC(-127.0.0.1:39389): stderr     from torch._C import *  # noqa: F403
3:01PM DBG GRPC(-127.0.0.1:39389): stderr ImportError: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

**Additional context**

**Comment by fakezeta** [comment]
Need to investigate why pip does not install the version of intel-extension-for-pytorch linked to MKL2024.1

**Comment by fakezeta** [comment]
Thanks to @gericho for raising the issue to me and providing logs: can you try now that the PR has been merged?
