### ISSUE TITLE
Chat WebUI stops updating

### ISSUE THREAD

**Issue by sozercan** [mudler/LocalAI#2491]
**LocalAI version:**
v2.16.0

**Environment, CPU architecture, OS, and Version:**

Running inside a container on linux/amd64, avx2

**Describe the bug**

WebUI chat stops updating the UI, and message gets cut. However, I can see the response is still streaming in the localai backend logs.

This happens in random places in the chat (sometimes early on, sometimes later), but it's consistent in every message (seems more likely to happen if response is longer). 
Also, happens with multiple different models, both pre-installed and downloaded from gallery.

<img width="1661" alt="Screenshot 2024-06-05 at 13 46 43" src="https://github.com/mudler/LocalAI/assets/852750/f1fb4800-558f-4fb5-926d-647478cd1983">

<img width="907" alt="image" src="https://github.com/mudler/LocalAI/assets/852750/9f447570-d4bf-4c58-ac52-f90ba67c1f3b">

**To Reproduce**

Send a message.

**Expected behavior**

It continues with the full response.

**Logs**

No issues on the backend side.
However, I see this in my browser console
Safari:
```
[Error] Unhandled Promise Rejection: SyntaxError: JSON Parse error: Unterminated string
	parse (chat.js:191)
	(anonymous function) (chat.js:191)
	forEach
	(anonymous function) (chat.js:184)
```

Edge:
```
VM162:1  Uncaught (in promise) SyntaxError: Unterminated string in JSON at position 133 (line 1 column 134)
    at JSON.parse (<anonymous>)
    at chat.js:191:28
    at Array.forEach (<anonymous>)
    at promptGPT (chat.js:184:11)
(anonymous) @ chat.js:191
promptGPT @ chat.js:184
await in promptGPT (async)
submitPrompt @ chat.js:53
eval @ VM92:3
[Alpine] if (!shiftPressed) { submitPrompt($event); } @ VM92:3
(anonymous) @ alpine.js:5
nr @ alpine.js:1
(anonymous) @ alpine.js:5
o @ alpine.js:5
(anonymous) @ alpine.js:5
(anonymous) @ alpine.js:5
```
**Additional context**

I can reproduce with Safari 17.5 and Edge 125

**Comment by sozercan** [comment]
It seems like `data` gets cut. Example:

```
"data: {"created":1717585880,"object":"chat.completion.chunk","id":"2575c60e-2a25-458b-b9b2-6b9cf308a93e","model":"llama-3-8b-instruct","cho"
```
